# FROM golang:GOVERSION As builder

# WORKDIR /app
# RUN apt-get update && \
#     apt-get upgrade -y && \
#     apt-get install build-essential -y
# ADD ./ .
# RUN CGO_ENABLED=1 go install github.com/mattn/go-sqlite3
# RUN go build -o app

FROM BASE_CONTANER As builder
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y curl gcc git locales locales-all &&\
    locale-gen ja_JP.UTF-8
RUN curl -OL https://go.dev/dl/goGOVERSION.linux-arm64.tar.gz &&\
    tar -C /usr/local -xzf goGOVERSION.linux-arm64.tar.gz &&\
    rm -rf goGOVERSION.linux-arm64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
WORKDIR /app
ADD ./ .
RUN go build -o app

FROM BASE_CONTANER
LABEL version="TAG"
LABEL name="APPNAME"
LABEL goversion="GOVERSION"
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl poppler-utils glibc-source && \
    locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN chown 1000:1000 /app
ENV PYROSCOPE_FLAG false
USER 1000
RUN mkdir -p public upload/pdf upload/zip db tmp html
ADD ./html ./html
ADD ./version ./
COPY --from=builder /app/app /app
CMD ["./app"]
