FROM golang:GOVERSION As builder

WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y
ADD ./ .
RUN go build -o app

FROM BASE_CONTANER
LABEL version="TAG"
LABEL name="APPNAME"
LABEL goversion="GOVERSION"
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl poppler-utils && \
    locale-gen ja_JP.UTF-8 
RUN apt-get update &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN chown 1000:1000 /app
ENV PYROSCOPE_FLAG false
USER 1000
RUN mkdir -p public upload/pdf upload/zip db tmp html
ADD ./html ./html
RUN rm -rf ./html/img/*
ADD ./version ./
COPY --from=builder /app/app /app
CMD ["./app"]